/**
 * JSX page components for ConvexDoc static HTML output.
 * Uses jsx-async-runtime; attributes are HTML-style (class, not className).
 */
/// <reference types="jsx-async-runtime" />

import type {
	ConvexFunctionSpec,
	ConvexModule,
	ParsedFunctionSpec,
} from "./function-spec.js";

export interface PageProps {
	title: string;
	/** Base path for links e.g. "" or "docs/" so links work from subdirs */
	baseHref?: string;
}

export interface IndexPageProps extends PageProps {
	spec: ParsedFunctionSpec;
	/** Slug for each module for linking (e.g. "tasks", "root") */
	moduleSlugs: Map<string, string>;
}

export interface ModulePageProps extends PageProps {
	module: ConvexModule;
	/** Pre-formatted validator strings for args/returns */
	formatArgs: (fn: ConvexFunctionSpec) => string;
	formatReturns: (fn: ConvexFunctionSpec) => string;
}

function functionTypeBadge(type: string): string {
	switch (type) {
		case "query":
			return "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300";
		case "mutation":
			return "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300";
		case "action":
			return "bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300";
		case "httpAction":
			return "bg-cyan-100 text-cyan-800 dark:bg-cyan-900/30 dark:text-cyan-300";
		default:
			return "bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300";
	}
}

function Layout({
	children,
	title,
	baseHref = "",
}: PageProps & { children: unknown }) {
	return (
		<>
			{{ html: `<!DOCTYPE html>` }}
			<html lang="en" class="scroll-pt-16">
				<head>
					<meta charset="utf-8" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<title>{title} — ConvexDoc</title>
					<link rel="stylesheet" href={`${baseHref}styles.css`} />
				</head>
				<body class="min-h-screen bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 font-sans antialiased">
					<header class="sticky top-0 z-10 border-b border-gray-200 dark:border-gray-700 bg-white/95 dark:bg-gray-800/95 backdrop-blur">
						<nav class="max-w-5xl mx-auto px-4 py-3 flex items-center gap-4">
							<a
								href={baseHref ? `${baseHref}index.html` : "index.html"}
								class="font-semibold text-lg text-inherit hover:text-blue-600 dark:hover:text-blue-400"
							>
								ConvexDoc
							</a>
						</nav>
					</header>
					<main class="max-w-5xl mx-auto px-4 py-8">{children}</main>
					<footer class="border-t border-gray-200 dark:border-gray-700 mt-12">
						<div class="max-w-5xl mx-auto px-4 py-4 text-sm text-gray-500 dark:text-gray-400">
							Generated by ConvexDoc
						</div>
					</footer>
				</body>
			</html>
		</>
	);
}

export function IndexPage({
	spec,
	moduleSlugs,
	title,
	baseHref = "",
}: IndexPageProps) {
	const { summary, modules } = spec;
	return (
		<Layout title={title} baseHref={baseHref}>
			<h1 class="text-3xl font-bold mb-2">API Overview</h1>
			<p class="text-gray-600 dark:text-gray-400 mb-8">
				Documentation for your Convex deployment functions.
			</p>

			<section class="mb-10">
				<h2 class="text-xl font-semibold mb-4">Summary</h2>
				<div class="grid grid-cols-2 sm:grid-cols-4 gap-3">
					<div class="rounded-lg border border-gray-200 dark:border-gray-700 p-4">
						<div class="text-2xl font-bold text-gray-900 dark:text-white">
							{summary.total}
						</div>
						<div class="text-sm text-gray-500 dark:text-gray-400">Total</div>
					</div>
					<div class="rounded-lg border border-gray-200 dark:border-gray-700 p-4">
						<div class="text-2xl font-bold text-blue-600 dark:text-blue-400">
							{summary.queries}
						</div>
						<div class="text-sm text-gray-500 dark:text-gray-400">Queries</div>
					</div>
					<div class="rounded-lg border border-gray-200 dark:border-gray-700 p-4">
						<div class="text-2xl font-bold text-green-600 dark:text-green-400">
							{summary.mutations}
						</div>
						<div class="text-sm text-gray-500 dark:text-gray-400">
							Mutations
						</div>
					</div>
					<div class="rounded-lg border border-gray-200 dark:border-gray-700 p-4">
						<div class="text-2xl font-bold text-purple-600 dark:text-purple-400">
							{summary.actions}
						</div>
						<div class="text-sm text-gray-500 dark:text-gray-400">Actions</div>
					</div>
					{summary.httpActions > 0 ? (
						<div class="rounded-lg border border-gray-200 dark:border-gray-700 p-4">
							<div class="text-2xl font-bold text-cyan-600 dark:text-cyan-400">
								{summary.httpActions}
							</div>
							<div class="text-sm text-gray-500 dark:text-gray-400">
								HTTP Actions
							</div>
						</div>
					) : null}
				</div>
			</section>

			<section>
				<h2 class="text-xl font-semibold mb-4">Modules</h2>
				<ul class="space-y-2">
					{modules.map((mod) => {
						const slug = moduleSlugs.get(mod.name) ?? mod.name;
						const href = slug === "index" ? "index.html" : `${slug}.html`;
						return (
							<li>
								<a
									href={baseHref ? `${baseHref}${href}` : href}
									class="block rounded-lg border border-gray-200 dark:border-gray-700 p-4 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
								>
									<span class="font-medium">{mod.name}</span>
									<span class="text-gray-500 dark:text-gray-400 ml-2">
										({mod.functions.length} function
										{mod.functions.length === 1 ? "" : "s"})
									</span>
								</a>
							</li>
						);
					})}
				</ul>
			</section>
		</Layout>
	);
}

export function ModulePage({
	module,
	formatArgs,
	formatReturns,
	title,
	baseHref = "",
}: ModulePageProps) {
	const indexHref = baseHref ? `${baseHref}index.html` : "index.html";
	return (
		<Layout title={title} baseHref={baseHref}>
			<nav class="text-sm text-gray-500 dark:text-gray-400 mb-4">
				<a
					href={indexHref}
					class="hover:text-gray-700 dark:hover:text-gray-300"
				>
					Overview
				</a>
				<span class="mx-2">/</span>
				<span class="text-gray-900 dark:text-white">{module.name}</span>
			</nav>

			<h1 class="text-3xl font-bold mb-2">{module.name}</h1>
			<p class="text-gray-600 dark:text-gray-400 mb-8">
				{module.functions.length} function
				{module.functions.length === 1 ? "" : "s"} in this module.
			</p>

			<ul class="space-y-6">
				{module.functions.map((fn) => {
					const argsStr = formatArgs(fn);
					const returnsStr = formatReturns(fn);
					return (
						<li
							id={`fn-${fn.identifier.replace(/:/g, "-")}`}
							class="rounded-lg border border-gray-200 dark:border-gray-700 p-5 bg-white dark:bg-gray-800/50"
						>
							<div class="flex flex-wrap items-center gap-2 mb-2">
								<span
									class={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${functionTypeBadge(fn.functionType)}`}
								>
									{fn.functionType}
								</span>
								{fn.visibility.kind === "internal" ? (
									<span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-400">
										internal
									</span>
								) : null}
								<span class="font-mono font-semibold">{fn.identifier}</span>
							</div>
							{argsStr !== "none" ? (
								<div class="text-sm mt-2">
									<span class="text-gray-500 dark:text-gray-400">args:</span>{" "}
									<code class="text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 px-1 rounded">
										{argsStr}
									</code>
								</div>
							) : null}
							{returnsStr !== "none" ? (
								<div class="text-sm mt-1">
									<span class="text-gray-500 dark:text-gray-400">returns:</span>{" "}
									<code class="text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 px-1 rounded">
										{returnsStr}
									</code>
								</div>
							) : null}
						</li>
					);
				})}
			</ul>
		</Layout>
	);
}
